Topdown_GlobalRs.Rmd
data/Fire_burn_C.csv
data/GlobalRs.csv
functions.R

Please accept this pull request

mark down document updated according to Ben's github issues

---

Topdown_GlobalRs.Rmd
functions.R

Using geom_quasirandom instead of geom_jitter

supplemental figures plot updated

---

Resampling_test.Rmd
Resampling_test_bbl.Rmd
Topdown_GlobalRs.Rmd
data/GlobalRs.csv
functions.R

resampling methods comparison added

---

Topdown_GlobalRs.Rmd
functions.R

Let's discuss on Thursday. This includes minor fixes, but also suggested changes to the abstract.
Re the abstract, let's talk. The last sentence:
>The reasons of the inconsistency need further study for better understanding global terrestrial carbon cycling in the future.
...is OK for a 'normal' journal, but not for _Nature_.

Small fixes

---

Topdown_GlobalRs.Rmd

Split CMIP6 into global and local

---

data/GlobalRs.csv

Add header

---

Topdown_GlobalRs.Rmd
functions-resampling.R
functions-stats.R
functions.R
toyproblem_overlap.Rmd
toyproblem_overlap_normalOnly.Rmd

Toy problem as discussed in https://github.com/jinshijian/GlobalC/issues/52

The toy problem R markdown

---

Topdown_GlobalRs.Rmd
functions-stats.R
toyproblem_overlap.Rmd

Implement method in `toyproblem_overlap.Rmd` code by @abigailsnyder see #61
Closes #52

Implement overlap calculation

---

Resampling_test_bbl.Rmd
Topdown_GlobalRs.Rmd
functions.R

Hello Ben, I cleaned the functions and changed the parameter names for functions when necessary. Thanks

function clean and better parameter names

---

functions.R

the viriance_decomp function was defined at two places, deleted one

delete the duplicate function-variance_decomp

---

Topdown_GlobalRs.Rmd

Using subscript instead of 'Top-down' and 'Bottom-up'

Using subscript instead of Top-Down and Bottom-up

---

Topdown_GlobalRs.Rmd

Implement new joint-prob figure discussed at AGU

---

Topdown_GlobalRs.Rmd

Update markdown for figures

---

Topdown_GlobalRs.Rmd

Facet Figure 3

---

Resampling_test_bbl.Rmd
Topdown_GlobalRs.Rmd
data/GlobalGPP_Sum.csv

Update GPP by group figure and get values for overlap group

Update GPP by group figure

---

Topdown_GlobalRs.Rmd
cmip/1A.CMIP6_v_Obs_Comparison.Rmd
cmip/1A.global_RstoGPP_processing.Rmd

The final CMIP6 work flow and modified Topdown_Global to incorporate the data.

Cmip analysis reproducible

---

Resampling_test_bbl.Rmd
Topdown_GlobalRs.Rmd
cmip/1A.CMIP6_v_Obs_Comparison.Rmd
cmip/1A.global_RstoGPP_processing.Rmd
functions-resampling.R
functions-stats.R
functions.R
toyproblem_overlap.Rmd
toyproblem_overlap_normalOnly.Rmd

@jinshijian Please take a careful look–if you don't like it, we don't have to do this.
This PR touches every code file, because I ran the entire directory through the [styler package](https://styler.r-lib.org), using the default `tidyverse_style`. I think it makes things consistent and easier to read, but again, Jinshi this is your call.
Feedback welcome from you too @kdorheim

Apply consistent style to code

---

Topdown_GlobalRs.Rmd
functions.R

More check on getting rid of goofy line breaks

Goofy line breaks

---

functions-calc_bootstrap.R

Explanation on Rshoot to Rroot ratio corrected

Rshoot to Rroot ratio explanation correction

---

Topdown_GlobalRs.Rmd
functions.R

Figure update

---

Topdown_GlobalRs.Rmd

Figure 3 x-axis update

---

Topdown_GlobalRs.Rmd

Small changes for better figure visualization

---

Topdown_GlobalRs.Rmd

Jj fig mod

---

Topdown_GlobalRs.Rmd
data/GlobalGPP_Sum.csv

Figure 1 and 2 are combined together

Combine Figure 1

---

GlobalRs_Modeling.Rmd

Global Rs modeling Rmd added notes for better understanding

Global Rs modeling Rmd added notes for better understanding

---

Topdown_GlobalRs.Rmd

Update Figure 1

---

GlobalC_nc_revision.Rmd
Topdown_GlobalRs.Rmd
data/GlobalRs.csv
functions-calc_bootstrap.R
functions.R

NC revision

---

Topdown_GlobalRs.Rmd

Update figure captions
